#!/bin/bash
# Generate badges for README

BADGES_FILE="docs/badges.md"

echo "Generating badges..."

cat > "$BADGES_FILE" << 'EOF'
<!-- Auto-generated by scripts/generate-badges.sh -->

| Badge | URL |
|-------|-----|
| Python | ![Python](https://img.shields.io/badge/python-3.11%2B-blue) |
| License | ![License](https://img.shields.io/badge/license-MIT-blue) |
| CI | ![CI](https://github.com/vidrev/vidrev/workflows/CI/badge.svg) |
| Dependencies | ![Dependencies](https://img.shields.io/badge/dependencies-up%20to%20date-brightgreen) |
EOF

echo "Badges generated at $BADGES_FILE"
